export const REACT_BEARER_KEY = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwOGM2YWIwNzY1Y2M5MTk1OGIzZmFkZjkwNDZmMTUzZCIsInN1YiI6IjYyZTdjZjVjN2NhYTQ3MDA1YjM0MTZiYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.SzlP6e3rOAQg_GWkzmW-NFVmp7Wui72kiN3v5k-h2hE"
export const REACT_API_KEY = "08c6ab0765cc91958b3fadf9046f153d"
export const REACT_BASE_URL = "https://api.themoviedb.org/3"
export const REACT_IMAGE_PATH = "https://image.tmdb.org/t/p/original"
export const REACT_URL_IMAGE = "https://image.tmdb.org/t/p/original"